-- -------------------------------------
-- --      BOA database creation      --
-- -------------------------------------
-- --       Database structure        --
-- --          for BOA V3.2           --
-- -------------------------------------
-- --     1- Tables description       --
-- -------------------------------------

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `BOA`
--

--

--
-- Table structure for table `action`
--

CREATE TABLE IF NOT EXISTS `action` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `AUTHOR` varchar(40) DEFAULT NULL,
  `LABEL` varchar(30) DEFAULT NULL,
  `LOGIN` varchar(15) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `COMMENT_ID` bigint(20) DEFAULT NULL,
  `HISTORY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_ACTION_COMMENT_ID` (`COMMENT_ID`),
  KEY `K_ACTION_HISTORY_ID` (`HISTORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `actionobso`
--

CREATE TABLE IF NOT EXISTS `actionobso` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `airbuspn`
--

CREATE TABLE IF NOT EXISTS `airbuspn` (
  `ID` bigint(20) NOT NULL,
  `IDENTIFIER` varchar(30) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AIRBUSPN_IDENTIFIER` (`IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `airbusstatus`
--

CREATE TABLE IF NOT EXISTS `airbusstatus` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  `COLORHEX` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `aircraftprogram`
--

CREATE TABLE IF NOT EXISTS `aircraftprogram` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AIRCRAFTPROGRAM_VALUE` (`DEFAULTVALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `article`
--

CREATE TABLE IF NOT EXISTS `article` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `AIRBUSSN` varchar(30) DEFAULT NULL,
  `STATE` varchar(20) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `MANUFACTURERSN` varchar(20) DEFAULT NULL,
  `ACQUISITIONDATE` datetime DEFAULT NULL,
  `CMSCODE` varchar(20) DEFAULT NULL,
  `USEDBY_INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `MANUFACTURERPN_ID` bigint(20) DEFAULT NULL,
  `TYPEARTICLE_ID` bigint(20) DEFAULT NULL,
  `AIRBUSPN_ID` bigint(20) DEFAULT NULL,
  `USEDBY_ARTICLE_ID` bigint(20) DEFAULT NULL,
  `HISTORY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_ARTICLE_AIRBUSSN` (`AIRBUSSN`),
  KEY `K_ARTICLE_HISTORY_ID` (`HISTORY_ID`),
  KEY `K_ARTICLE_USEDBY_INSTALLATION_ID` (`USEDBY_INSTALLATION_ID`),
  KEY `K_ARTICLE_USEDBY_ARTICLE_ID` (`USEDBY_ARTICLE_ID`),
  KEY `K_ARTICLE_MANUFACTURERPN_ID` (`MANUFACTURERPN_ID`),
  KEY `K_ARTICLE_AIRBUSPN_ID` (`AIRBUSPN_ID`),
  KEY `K_ARTICLE_TYPEARTICLE_ID` (`TYPEARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Table structure for table `boa_parameters`
--

DROP TABLE IF EXISTS `boa_parameters`;
CREATE TABLE `boa_parameters` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Table structure for table `board`
--

CREATE TABLE IF NOT EXISTS `board` (
  `ID` bigint(20) NOT NULL,
  `BOOTLOADER` varchar(30) DEFAULT NULL,
  `REVH` varchar(10) DEFAULT NULL,
  `CALIBRATION` tinyint(1) DEFAULT '0',
  `MACADDRESS` varchar(17) DEFAULT NULL,
  `REVS` varchar(10) DEFAULT NULL,
  `IPADDRESS` varchar(39) DEFAULT NULL,
  `ACTIVESTOCKCONTROLDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `board_communicationport`
--

CREATE TABLE IF NOT EXISTS `board_communicationport` (
  `BOARD_ID` bigint(20) NOT NULL,
  `COMMUNICATIONPORT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`BOARD_ID`,`COMMUNICATIONPORT_ID`),
  KEY `K_BOARD_COMMUNICATIONPORT_COMMUNICATIONPORT_ID` (`COMMUNICATIONPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `building`
--

CREATE TABLE IF NOT EXISTS `building` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_BUILDING_NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `businessallocationpc`
--

CREATE TABLE IF NOT EXISTS `businessallocationpc` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `businessusagepc`
--

CREATE TABLE IF NOT EXISTS `businessusagepc` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `cabinet`
--

CREATE TABLE IF NOT EXISTS `cabinet` (
  `ID` bigint(20) NOT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CABINET_DESIGNATION` (`DESIGNATION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `comment`
--

CREATE TABLE IF NOT EXISTS `comment` (
  `ID` bigint(20) NOT NULL,
  `MESSAGE` varchar(450) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `communicationport`
--

CREATE TABLE IF NOT EXISTS `communicationport` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `SOCKET` varchar(15) DEFAULT NULL,
  `MACADDRESS` varchar(17) DEFAULT NULL,
  `IPADDRESS` varchar(39) DEFAULT NULL,
  `FIXEDIP` tinyint(1) DEFAULT NULL,
  `NETWORK_ID` bigint(20) DEFAULT NULL,
  `MASK` varchar(39) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_COMMUNICATIONPORT_NETWORK_ID` (`NETWORK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `consultperiod`
--

CREATE TABLE IF NOT EXISTS `consultperiod` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  `MONTHNUMBER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `container`
--

CREATE TABLE IF NOT EXISTS `container` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `CABINET_ID` bigint(20) DEFAULT NULL,
  `RACK_ID` bigint(20) DEFAULT NULL,
  `PC_ID` bigint(20) DEFAULT NULL,
  `BOARD_ID` bigint(20) DEFAULT NULL,
  `TOOL_ID` bigint(20) DEFAULT NULL,
  `ARTICLE_ID` bigint(20) DEFAULT NULL,
  `LETTER` varchar(3) DEFAULT NULL,
  `RACKPOSITION` varchar(6) DEFAULT NULL,
  `SLOTNUMBER` int(11) DEFAULT NULL,
  `FACE` varchar(10) DEFAULT NULL,
  `COMMENT` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_CONTAINER_INSTALLATION_ID` (`INSTALLATION_ID`),
  KEY `K_CONTAINER_CABINET_ID` (`CABINET_ID`),
  KEY `K_CONTAINER_RACK_ID` (`RACK_ID`),
  KEY `K_CONTAINER_PC_ID` (`PC_ID`),
  KEY `K_CONTAINER_BOARD_ID` (`BOARD_ID`),
  KEY `K_CONTAINER_TOOL_ID` (`TOOL_ID`),
  KEY `K_CONTAINER_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `dated_comment`
--

CREATE TABLE IF NOT EXISTS `dated_comment` (
  `ID` bigint(20) NOT NULL,
  `ARTICLE_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `COMMENT` varchar(200) NOT NULL,
  `DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `demand`
--

CREATE TABLE IF NOT EXISTS `demand` (
  `ID` bigint(20) NOT NULL,
  `REQUESTNUMBER` varchar(20) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `TOREPLACE_PC_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `OWNER` varchar(100) DEFAULT NULL,
  `OWNERSIGLUM` varchar(20) DEFAULT NULL,
  `NEEDDATE` date DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `ALLOCATED_PC_ID` bigint(20) DEFAULT NULL,
  `CLOSUREDATE` date DEFAULT NULL,
  `DEPARTMENT` varchar(10) DEFAULT NULL,
  `PROGRAM` varchar(50) DEFAULT NULL,
  `PROJECT` varchar(50) DEFAULT NULL,
  `BUDGET` varchar(50) DEFAULT NULL,
  `JUSTIFICATION` varchar(100) DEFAULT NULL,
  `CONTACT` varchar(50) DEFAULT NULL,
  `COMMENTS` varchar(250) DEFAULT NULL,
  `TYPEPC_TYPEARTICLE_ID` bigint(20) DEFAULT NULL,
  `PRODUCTTYPEPC_ID` bigint(20) DEFAULT NULL,
  `PLUGNUMBER` varchar(15) DEFAULT NULL,
  `FEATURES` varchar(50) DEFAULT NULL,
  `ADDITIONALINFORMATION` varchar(250) DEFAULT NULL,
  `USEDBY_INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `USEDBY_ARTICLE_ID` bigint(20) DEFAULT NULL,
  `USEDBY_TOOL_ID` bigint(20) DEFAULT NULL,
  `BUSINESSUSAGEPC_ID` bigint(20) DEFAULT NULL,
  `BUSINESSALLOCATIONPC_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_DEMAND_TOREPLACE_PC_ID` (`TOREPLACE_PC_ID`),
  UNIQUE KEY `UK_DEMAND_ALLOCATED_PC_ID` (`ALLOCATED_PC_ID`),
  KEY `K_DEMAND_USER_ID` (`USER_ID`),
  KEY `K_DEMAND_TYPEPC_TYPEARTICLE_ID` (`TYPEPC_TYPEARTICLE_ID`),
  KEY `K_DEMAND_PRODUCTTYPEPC_ID` (`PRODUCTTYPEPC_ID`),
  KEY `K_DEMAND_USEDBY_INSTALLATION_ID` (`USEDBY_INSTALLATION_ID`),
  KEY `K_DEMAND_USEDBY_ARTICLE_ID` (`USEDBY_ARTICLE_ID`),
  KEY `K_DEMAND_USEDBY_TOOL_ID` (`USEDBY_TOOL_ID`),
  KEY `K_DEMAND_BUSINESSALLOCATIONPC_ID` (`BUSINESSALLOCATIONPC_ID`),
  KEY `K_DEMAND_BUSINESSUSAGEPC_ID` (`BUSINESSUSAGEPC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `departmentincharge`
--

CREATE TABLE IF NOT EXISTS `departmentincharge` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODIFIABLE` tinyint(1) DEFAULT 0,
  `DELETABLE` tinyint(1) DEFAULT 0,
  `DEFAULTVALUE` varchar(10) DEFAULT NULL,
  `DESCRIPTION` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_DEPARTMENTINCHARGE_VALUE` (`DEFAULTVALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `document`
--

CREATE TABLE IF NOT EXISTS `document` (
  `ID` bigint(20) NOT NULL,
  `ARTICLE_ID` bigint(20) DEFAULT NULL,
  `INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `TOOL_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `FILEBLOB` longblob NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `UPLOADDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_DOCUMENT_ARTICLE_ID` (`ARTICLE_ID`),
  KEY `K_DOCUMENT_INSTALLATION_ID` (`INSTALLATION_ID`),
  KEY `K_DOCUMENT_TOOL_ID` (`TOOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `domain`
--

CREATE TABLE IF NOT EXISTS `domain` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODIFIABLE` tinyint(1) DEFAULT 0,
  `DELETABLE` tinyint(1) DEFAULT 0,
  `DEFAULTVALUE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_DOMAIN_VALUE` (`DEFAULTVALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `externalentity`
--

CREATE TABLE IF NOT EXISTS `externalentity` (
  `ID` bigint(20) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `NAME` varchar(30) NOT NULL,
  `EXTERNALENTITYTYPE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_EXTERNALENTITY_NAME` (`NAME`),
  KEY `K_EXTERNALENTITY_EXTERNALENTITYTYPE_ID` (`EXTERNALENTITYTYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `externalentitytype`
--

CREATE TABLE IF NOT EXISTS `externalentitytype` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `fieldmodification`
--

CREATE TABLE IF NOT EXISTS `fieldmodification` (
  `ID` bigint(20) NOT NULL,
  `FIELD` varchar(35) DEFAULT NULL,
  `AFTERVALUE` varchar(140) DEFAULT NULL,
  `BEFOREVALUE` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `history`
--

CREATE TABLE IF NOT EXISTS `history` (
  `ID` bigint(20) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `GENERAL_COMMENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_HISTORY_GENERAL_COMMENT_ID` (`GENERAL_COMMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `installation`
--

CREATE TABLE IF NOT EXISTS `installation` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `COMMENTS` varchar(50) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `LABO_PLACE_ID` bigint(20) DEFAULT NULL,
  `HISTORY_ID` bigint(20) NOT NULL,
  `STARTINGDATE` date DEFAULT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `AIRCRAFTPROGRAM_ID` bigint(20) NOT NULL,
  `BUSINESSSIGLUM` varchar(30) NOT NULL,
  `USER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_INSTALLATION_NAME` (`NAME`),
  KEY `K_INSTALLATION_AIRCRAFTPROGRAM_ID` (`AIRCRAFTPROGRAM_ID`),
  KEY `K_INSTALLATION_LABO_PLACE_ID` (`LABO_PLACE_ID`),
  KEY `K_INSTALLATION_HISTORY_ID` (`HISTORY_ID`),
  KEY `K_INSTALLATION_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `location`
--

CREATE TABLE IF NOT EXISTS `location` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `INHERITED` tinyint(1) DEFAULT '0',
  `PLACE_ID` bigint(20) DEFAULT NULL,
  `EXTERNALENTITY_ID` bigint(20) DEFAULT NULL,
  `ARTICLE_ID` bigint(20) DEFAULT NULL,
  `DEMAND_ID` bigint(20) DEFAULT NULL,
  `TOOL_ID` bigint(20) DEFAULT NULL,
  `PRECISELOCATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_LOCATION_PLACE_ID` (`PLACE_ID`),
  KEY `K_LOCATION_EXTERNALENTITY_ID` (`EXTERNALENTITY_ID`),
  UNIQUE KEY `UK_LOCATION_ARTICLE_ID` (`ARTICLE_ID`),
  UNIQUE KEY `UK_LOCATION_DEMAND_ID` (`DEMAND_ID`),
  UNIQUE KEY `UK_LOCATION_TOOL_ID` (`TOOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `manufacturerpn`
--

CREATE TABLE IF NOT EXISTS `manufacturerpn` (
  `ID` bigint(20) NOT NULL,
  `IDENTIFIER` varchar(30) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MANUFACTURERPN_IDENTIFIER` (`IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `manufacturerstatus`
--

CREATE TABLE IF NOT EXISTS `manufacturerstatus` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  `COLORHEX` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `mat_view_article`
--

CREATE TABLE IF NOT EXISTS `mat_view_article` (
  `ID` bigint(20) NOT NULL,
  `C_PLACE_ID` bigint(20) DEFAULT NULL,
  UNIQUE KEY `UK_MATVIEWARTICLE_ID` (`ID`),
  KEY `K_MATVIEWARTICLE_C_PLACE_ID` (`C_PLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `memoryslot`
--

CREATE TABLE IF NOT EXISTS `memoryslot` (
  `ID` bigint(20) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `NAME` varchar(15) NOT NULL,
  `USED` tinyint(1) DEFAULT '0',
  `MEMORYSIZE` varchar(30) DEFAULT NULL,
  `MEMORYTYPE` varchar(70) DEFAULT NULL,
  `PC_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MEMORYSLOT_PC_ID_NAME` (`PC_ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `network`
--

CREATE TABLE IF NOT EXISTS `network` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `obsolescencedata`
--

CREATE TABLE IF NOT EXISTS `obsolescencedata` (
  `ID` bigint(20) NOT NULL,
  `LASTOBSOLESCENCEUPDATE` date DEFAULT NULL,
  `ENDOFORDERDATE` date DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `ENDOFPRODUCTIONDATE` date DEFAULT NULL,
  `PERSONINCHARGE` varchar(60) DEFAULT NULL,
  `OBSOLESCENCEDATE` date DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `MTBF` bigint(20) DEFAULT NULL,
  `ENDOFSUPPORTDATE` date DEFAULT NULL,
  `COMMENTONSTRATEGY` varchar(1024) DEFAULT NULL,
  `SUPPLIER` varchar(50) DEFAULT NULL,
  `CONTINUITYDATE` date DEFAULT NULL,
  `ACTIONOBSO_ID` bigint(20) DEFAULT NULL,
  `TYPEPC_TYPEARTICLE_ID` bigint(20) DEFAULT NULL,
  `MANUFACTURERSTATUS_ID` bigint(20) DEFAULT NULL,
  `AIRBUSSTATUS_ID` bigint(20) DEFAULT NULL,
  `AIRBUSPN_ID` bigint(20) DEFAULT NULL,
  `TYPEARTICLE_ID` bigint(20) DEFAULT NULL,
  `SOFTWARE_ID` bigint(20) DEFAULT NULL,
  `STRATEGY_ID` bigint(20) DEFAULT NULL,
  `CONSULTPERIOD_ID` bigint(20) DEFAULT NULL,
  `MANUFACTURERPN_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_OBSOLESCENCEDATA_TYPEPC_TYPEARTICLE_ID` (`TYPEPC_TYPEARTICLE_ID`),
  UNIQUE KEY `UK_OBSOLESCENCEDATA_AIRBUSPN_ID_TYPEARTICLE_ID` (`AIRBUSPN_ID`,`TYPEARTICLE_ID`),
  UNIQUE KEY `UK_OBSOLESCENCEDATA_SOFTWARE_ID` (`SOFTWARE_ID`),
  UNIQUE KEY `UK_OBSOLESCENCEDATA_MANUFACTURERPN_ID_TYPEARTICLE_ID` (`MANUFACTURERPN_ID`,`TYPEARTICLE_ID`),
  KEY `K_OBSOLESCENCEDATA_AIRBUSSTATUS_ID` (`AIRBUSSTATUS_ID`),
  KEY `K_OBSOLESCENCEDATA_ACTIONOBSO_ID` (`ACTIONOBSO_ID`),
  KEY `K_OBSOLESCENCEDATA_STRATEGY_ID` (`STRATEGY_ID`),
  KEY `K_OBSOLESCENCEDATA_MANUFACTURERSTATUS_ID` (`MANUFACTURERSTATUS_ID`),
  KEY `K_OBSOLESCENCEDATA_CONSULTPERIOD_ID` (`CONSULTPERIOD_ID`),
  KEY `K_OBSOLESCENCEDATA_TYPEARTICLE_ID` (`TYPEARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `pc`
--

CREATE TABLE IF NOT EXISTS `pc` (
  `ID` bigint(20) NOT NULL,
  `ASSIGNMENT` varchar(50) DEFAULT NULL,
  `ADMIN` varchar(100) DEFAULT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `DEPARTMENTINCHARGE_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `OWNER` varchar(100) DEFAULT NULL,
  `OWNERSIGLUM` varchar(20) DEFAULT NULL,
  `USESTATE` varchar(20) DEFAULT NULL,
  `COMMENT` varchar(450) DEFAULT NULL,
  `FUNCTION` varchar(50) DEFAULT NULL,
  `NBSCREENS` int(11) DEFAULT NULL,
  `PRODUCTTYPEPC_ID` bigint(20) DEFAULT NULL,
  `BUSINESSUSAGEPC_ID` bigint(20) DEFAULT NULL,
  `BUSINESSALLOCATIONPC_ID` bigint(20) DEFAULT NULL,
  `AVAILABILITYSTATUS` varchar(20) DEFAULT NULL,
  `AVAILABILITYDATE` date DEFAULT NULL,
  `AUTOUPDATE` tinyint(1) DEFAULT '0',
  `LASTAUTOUPDATEDATE` datetime DEFAULT NULL,
  `LASTAUTOUPDATETYPE` varchar(10) DEFAULT NULL,
  `AUTODATAVALIDITYDATE` datetime DEFAULT NULL,
  `DEFAULTOS_SOFTWARE_ID` bigint(20) DEFAULT NULL,
  `DOMAIN_ID` bigint(20) DEFAULT NULL,
  `PLATFORM` varchar(20) DEFAULT NULL,
  `CPUTYPE` varchar(50) DEFAULT NULL,
  `CPUMAXSPEED` varchar(15) DEFAULT NULL,
  `CPUSOCKETS` int(11) DEFAULT NULL,
  `CPUCOREPERSOCKET` int(11) DEFAULT NULL,
  `CPULOGICALCPUPERSOCKET` int(11) DEFAULT NULL,
  `CPUTOTALLOGICALCPUS` int(11) DEFAULT NULL,
  `CPUHYPERTHREADING` varchar(15) DEFAULT NULL,
  `TOTALMEMORYSIZE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_PC_NAME` (`NAME`),
  KEY `K_PC_BUSINESSALLOCATIONPC_ID` (`BUSINESSALLOCATIONPC_ID`),
  KEY `K_PC_BUSINESSUSAGEPC_ID` (`BUSINESSUSAGEPC_ID`),
  KEY `K_PC_PRODUCTTYPEPC_ID` (`PRODUCTTYPEPC_ID`),
  KEY `K_PC_USER_ID` (`USER_ID`),
  KEY `K_PC_DEFAULTOS_SOFTWARE_ID` (`DEFAULTOS_SOFTWARE_ID`),
  KEY `K_PC_DOMAIN_ID` (`DOMAIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `pc_communicationport`
--

CREATE TABLE IF NOT EXISTS `pc_communicationport` (
  `PC_ID` bigint(20) NOT NULL,
  `COMMUNICATIONPORT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PC_ID`,`COMMUNICATIONPORT_ID`),
  KEY `K_PC_COMMUNICATIONPORT_COMMUNICATIONPORT_ID` (`COMMUNICATIONPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `pc_specificity`
--

CREATE TABLE IF NOT EXISTS `pc_specificity` (
  `ID` bigint(20) NOT NULL,
  `PC_ID` bigint(20) NOT NULL,
  `DESCRIPTION` varchar(200) NOT NULL,
  `CONTACT` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `permission`
--

CREATE TABLE IF NOT EXISTS `permission` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `CATEGORY` varchar(40) NOT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  `BITWISECODE` tinyint(3) unsigned NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_PERMISSION_CATEGORY_ROLE` (`CATEGORY`,`ROLE_ID`),
  KEY `FK_PERMISSION_ROLE_ID` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `place`
--

CREATE TABLE IF NOT EXISTS `place` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `TYPE` varchar(15) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `BUILDING_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_PLACE_NAME_BUILDING` (`NAME`,`BUILDING_ID`),
  KEY `K_PLACE_BUILDING_ID` (`BUILDING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `producttypepc`
--

CREATE TABLE IF NOT EXISTS `producttypepc` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `rack`
--

CREATE TABLE IF NOT EXISTS `rack` (
  `ID` bigint(20) NOT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `reminder`
--

CREATE TABLE IF NOT EXISTS `reminder` (
  `ID` bigint(20) NOT NULL,
  `TARGETDATE` date NOT NULL,
  `NBDAYSNOTIFICATION` int(11) NOT NULL,
  `ARTICLE_ID` bigint(20) DEFAULT NULL,
  `INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `TOOL_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `OBJECT` varchar(254) NOT NULL,
  `COMPLETED` tinyint(4) NOT NULL DEFAULT '0',
  `REMINDERSTATUS` varchar(15) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_REMINDER_USER_ID` (`USER_ID`),
  KEY `K_REMINDER_ARTICLE_ID` (`ARTICLE_ID`),
  KEY `FK_REMINDER_INSTALLATION_ID` (`INSTALLATION_ID`),
  KEY `FK_REMINDER_TOOL_ID` (`TOOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `role`
--

CREATE TABLE IF NOT EXISTS `role` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `SEQUENCE`
--

CREATE TABLE IF NOT EXISTS `SEQUENCE` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `software`
--

CREATE TABLE IF NOT EXISTS `software` (
  `ID` bigint(20) NOT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `LICENCE` varchar(40) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(512) DEFAULT NULL,
  `OPERATINGSYSTEM` tinyint(1) DEFAULT '0',
  `LASTUPDATE` datetime DEFAULT NULL,
  `NAME` varchar(50) NOT NULL,
  `DISTRIBUTION` varchar(50) NOT NULL,
  `KERNEL` varchar(50) NOT NULL,
  `MANUFACTURER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_SOFTWARE_NAME_DISTRIBUTION_KERNEL` (`NAME`,`DISTRIBUTION`,`KERNEL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `software_article`
--

CREATE TABLE IF NOT EXISTS `software_article` (
  `SOFTWARE_ID` bigint(20) NOT NULL,
  `ARTICLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`SOFTWARE_ID`,`ARTICLE_ID`),
  KEY `K_SOFTWARE_ARTICLE_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `software_demand`
--

CREATE TABLE IF NOT EXISTS `software_demand` (
  `SOFTWARE_ID` bigint(20) NOT NULL,
  `DEMAND_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`SOFTWARE_ID`,`DEMAND_ID`),
  KEY `K_SOFTWARE_DEMAND_DEMAND_ID` (`DEMAND_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `stock_selection`
--

CREATE TABLE IF NOT EXISTS `stock_selection` (
  `ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_STOCK_SELECTION_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `stock_selection_types`
--

CREATE TABLE IF NOT EXISTS `stock_selection_types` (
  `STOCKSELECTION_ID` bigint(20) NOT NULL,
  `TYPEARTICLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`STOCKSELECTION_ID`,`TYPEARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `strategy`
--

CREATE TABLE IF NOT EXISTS `strategy` (
  `ID` bigint(20) NOT NULL,
  `MODIFIABLE` tinyint(1) DEFAULT '0',
  `DELETABLE` tinyint(1) DEFAULT '0',
  `DEFAULTVALUE` varchar(60) DEFAULT NULL,
  `FRENCHVALUE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `switch`
--

CREATE TABLE IF NOT EXISTS `switch` (
  `ID` bigint(20) NOT NULL,
  `IPADDRESS` varchar(39) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `temp_child_items`
--

CREATE TABLE IF NOT EXISTS `temp_child_items` (
  `ID` bigint(20) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  UNIQUE KEY `UK_TEMPCHILDITEMS_ID_TYPE` (`ID`,`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `temp_parent_items`
--

CREATE TABLE IF NOT EXISTS `temp_parent_items` (
  `ID` bigint(20) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  UNIQUE KEY `UK_TEMPPARENTITEMS_ID_TYPE` (`ID`,`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `tool`
--

CREATE TABLE IF NOT EXISTS `tool` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `PERSONINCHARGE` varchar(40) DEFAULT NULL,
  `LOANDATE` date DEFAULT NULL,
  `LOANDUEDATE` date DEFAULT NULL,
  `COMMENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_TOOL_NAME` (`NAME`),
  KEY `K_TOOL_COMMENT_ID` (`COMMENT_ID`),
  KEY `K_TOOL_INSTALLATION_ID` (`INSTALLATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `typearticle`
--

CREATE TABLE IF NOT EXISTS `typearticle` (
  `ID` bigint(20) NOT NULL,
  `DTYPE` varchar(31) DEFAULT NULL,
  `LABEL` varchar(60) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `MANUFACTURER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_TYPEARTICLE_LABEL` (`LABEL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `typearticle_airbuspn`
--

CREATE TABLE IF NOT EXISTS `typearticle_airbuspn` (
  `TYPEARTICLE_ID` bigint(20) NOT NULL,
  `AIRBUSPN_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`TYPEARTICLE_ID`,`AIRBUSPN_ID`),
  KEY `K_TYPEARTICLE_AIRBUSPN_AIRBUSPN_ID` (`AIRBUSPN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `ID` bigint(20) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `LASTNAME` varchar(40) DEFAULT NULL,
  `LOGIN` varchar(15) DEFAULT NULL,
  `FIRSTNAME` varchar(25) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  `PASSWORD` varchar(32) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `RECEIVEBOAMAIL` tinyint(1) DEFAULT '1',
  `LASTLOGGEDIN` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_LOGIN` (`LOGIN`),
  KEY `FK_USER_ROLE_ID` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--

--
-- Table structure for table `various`
--

CREATE TABLE IF NOT EXISTS `various` (
  `ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `action`
--
ALTER TABLE `action`
  ADD CONSTRAINT `FK_ACTION_COMMENT_ID` FOREIGN KEY (`COMMENT_ID`) REFERENCES `comment` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ACTION_HISTORY_ID` FOREIGN KEY (`HISTORY_ID`) REFERENCES `history` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `article`
--
ALTER TABLE `article`
  ADD CONSTRAINT `FK_ARTICLE_USEDBY_INSTALLATION_ID` FOREIGN KEY (`USEDBY_INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ARTICLE_MANUFACTURERPN_ID` FOREIGN KEY (`MANUFACTURERPN_ID`) REFERENCES `manufacturerpn` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ARTICLE_TYPEARTICLE_ID` FOREIGN KEY (`TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ARTICLE_AIRBUSPN_ID` FOREIGN KEY (`AIRBUSPN_ID`) REFERENCES `airbuspn` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ARTICLE_USEDBY_ARTICLE_ID` FOREIGN KEY (`USEDBY_ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_ARTICLE_HISTORY_ID` FOREIGN KEY (`HISTORY_ID`) REFERENCES `history` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `board`
--
ALTER TABLE `board`
  ADD CONSTRAINT `FK_BOARD_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `board_communicationport`
--
ALTER TABLE `board_communicationport`
  ADD CONSTRAINT `FK_BOARD_COMMUNICATIONPORT_BOARD_ID` FOREIGN KEY (`BOARD_ID`) REFERENCES `board` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_BOARD_COMMUNICATIONPORT_COMMUNICATIONPORT_ID` FOREIGN KEY (`COMMUNICATIONPORT_ID`) REFERENCES `communicationport` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `cabinet`
--
ALTER TABLE `cabinet`
  ADD CONSTRAINT `FK_CABINET_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `communicationport`
--
ALTER TABLE `communicationport`
  ADD CONSTRAINT `FK_COMMUNICATIONPORT_NETWORK_ID` FOREIGN KEY (`NETWORK_ID`) REFERENCES `network` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `container`
--
ALTER TABLE `container`
  ADD CONSTRAINT `FK_CONTAINER_INSTALLATION_ID` FOREIGN KEY (`INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_CABINET_ID` FOREIGN KEY (`CABINET_ID`) REFERENCES `cabinet` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_RACK_ID` FOREIGN KEY (`RACK_ID`) REFERENCES `rack` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_PC_ID` FOREIGN KEY (`PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_BOARD_ID` FOREIGN KEY (`BOARD_ID`) REFERENCES `board` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_TOOL_ID` FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CONTAINER_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
  
--
-- Constraints for table `dated_comment`
--
ALTER TABLE `dated_comment`
  ADD CONSTRAINT `FK_DATED_COMMMENT_PC_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DATED_COMMMENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `demand`
--
ALTER TABLE `demand`
  ADD CONSTRAINT `FK_DEMAND_TOREPLACE_PC_ID` FOREIGN KEY (`TOREPLACE_PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_ALLOCATED_PC_ID` FOREIGN KEY (`ALLOCATED_PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_TYPEPC_TYPEARTICLE_ID` FOREIGN KEY (`TYPEPC_TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_PRODUCTTYPEPC_ID` FOREIGN KEY (`PRODUCTTYPEPC_ID`) REFERENCES `producttypepc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_USEDBY_INSTALLATION_ID` FOREIGN KEY (`USEDBY_INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_USEDBY_ARTICLE_ID` FOREIGN KEY (`USEDBY_ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_USEDBY_TOOL_ID` FOREIGN KEY (`USEDBY_TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_BUSINESSUSAGEPC_ID` FOREIGN KEY (`BUSINESSUSAGEPC_ID`) REFERENCES `businessusagepc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEMAND_BUSINESSALLOCATIONPC_ID` FOREIGN KEY (`BUSINESSALLOCATIONPC_ID`) REFERENCES `businessallocationpc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `document`
--
ALTER TABLE `document`
  ADD CONSTRAINT `FK_DOCUMENT_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DOCUMENT_INSTALLATION_ID` FOREIGN KEY (`INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DOCUMENT_TOOL_ID` FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `externalentity`
--
ALTER TABLE `externalentity`
  ADD CONSTRAINT `FK_EXTERNALENTITY_EXTERNALENTITYTYPE_ID` FOREIGN KEY (`EXTERNALENTITYTYPE_ID`) REFERENCES `externalentitytype` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `fieldmodification`
--
ALTER TABLE `fieldmodification`
  ADD CONSTRAINT `FK_FIELDMODIFICATION_ID` FOREIGN KEY (`ID`) REFERENCES `action` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `history`
--
ALTER TABLE `history`
  ADD CONSTRAINT `FK_HISTORY_GENERAL_COMMENT_ID` FOREIGN KEY (`GENERAL_COMMENT_ID`) REFERENCES `comment` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `installation`
--
ALTER TABLE `installation`
  ADD CONSTRAINT `FK_INSTALLATION_AIRCRAFTPROGRAM_ID` FOREIGN KEY (`AIRCRAFTPROGRAM_ID`) REFERENCES `aircraftprogram` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_INSTALLATION_HISTORY_ID` FOREIGN KEY (`HISTORY_ID`) REFERENCES `history` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_INSTALLATION_LABO_PLACE_ID` FOREIGN KEY (`LABO_PLACE_ID`) REFERENCES `place` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_INSTALLATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `location`
--
ALTER TABLE `location`
  ADD CONSTRAINT `FK_LOCATION_PLACE_ID` FOREIGN KEY (`PLACE_ID`) REFERENCES `place` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_LOCATION_EXTERNALENTITY_ID` FOREIGN KEY (`EXTERNALENTITY_ID`) REFERENCES `externalentity` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_LOCATION_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_LOCATION_DEMAND_ID` FOREIGN KEY (`DEMAND_ID`) REFERENCES `demand` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_LOCATION_TOOL_ID` FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `mat_view_article`
--
ALTER TABLE `mat_view_article`
  ADD CONSTRAINT `FK_MATVIEWARTICLE_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_MATVIEWARTICLE_C_PLACE_ID` FOREIGN KEY (`C_PLACE_ID`) REFERENCES `place` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `memoryslot`
--
ALTER TABLE `memoryslot`
  ADD CONSTRAINT `FK_MEMORYSLOT_PC_ID` FOREIGN KEY (`PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `obsolescencedata`
--
ALTER TABLE `obsolescencedata`
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_AIRBUSSTATUS_ID` FOREIGN KEY (`AIRBUSSTATUS_ID`) REFERENCES `airbusstatus` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_ACTIONOBSO_ID` FOREIGN KEY (`ACTIONOBSO_ID`) REFERENCES `actionobso` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_STRATEGY_ID` FOREIGN KEY (`STRATEGY_ID`) REFERENCES `strategy` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_TYPEPC_TYPEARTICLE_ID` FOREIGN KEY (`TYPEPC_TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_MANUFACTURERSTATUS_ID` FOREIGN KEY (`MANUFACTURERSTATUS_ID`) REFERENCES `manufacturerstatus` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_AIRBUSPN_ID` FOREIGN KEY (`AIRBUSPN_ID`) REFERENCES `airbuspn` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_SOFTWARE_ID` FOREIGN KEY (`SOFTWARE_ID`) REFERENCES `software` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_CONSULTPERIOD_ID` FOREIGN KEY (`CONSULTPERIOD_ID`) REFERENCES `consultperiod` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_MANUFACTURERPN_ID` FOREIGN KEY (`MANUFACTURERPN_ID`) REFERENCES `manufacturerpn` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_OBSOLESCENCEDATA_TYPEARTICLE_ID` FOREIGN KEY (`TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `pc`
--
ALTER TABLE `pc`
  ADD CONSTRAINT `FK_PC_PRODUCTTYPEPC_ID` FOREIGN KEY (`PRODUCTTYPEPC_ID`) REFERENCES `producttypepc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_BUSINESSUSAGEPC_ID` FOREIGN KEY (`BUSINESSUSAGEPC_ID`) REFERENCES `businessusagepc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_BUSINESSALLOCATIONPC_ID` FOREIGN KEY (`BUSINESSALLOCATIONPC_ID`) REFERENCES `businessallocationpc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_DEFAULTOS_SOFWTARE_ID` FOREIGN KEY (`DEFAULTOS_SOFTWARE_ID`) REFERENCES `software` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_DOMAIN_ID` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `domain` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEPARTMENTINCHARGE_ID` FOREIGN KEY (`DEPARTMENTINCHARGE_ID`) REFERENCES `departmentincharge` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `pc_communicationport`
--
ALTER TABLE `pc_communicationport`
  ADD CONSTRAINT `FK_PC_COMMUNICATIONPORT_PC_ID` FOREIGN KEY (`PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_PC_COMMUNICATIONPORT_COMMUNICATIONPORT_ID` FOREIGN KEY (`COMMUNICATIONPORT_ID`) REFERENCES `communicationport` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
  
--
-- Constraints for table `pc_specificity`
--
ALTER TABLE `pc_specificity`
  ADD CONSTRAINT `FK_PC_SPECIFICITY_PC_ID` FOREIGN KEY (`PC_ID`) REFERENCES `pc` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
  
--
-- Constraints for table `permission`
--
ALTER TABLE `permission`
  ADD CONSTRAINT `FK_PERMISSION_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `place`
--
ALTER TABLE `place`
  ADD CONSTRAINT `FK_PLACE_BUILDING_ID` FOREIGN KEY (`BUILDING_ID`) REFERENCES `building` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `rack`
--
ALTER TABLE `rack`
  ADD CONSTRAINT `FK_RACK_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `reminder`
--
ALTER TABLE `reminder`
  ADD CONSTRAINT `FK_REMINDER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_REMINDER_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_REMINDER_INSTALLATION_ID` FOREIGN KEY (`INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_REMINDER_TOOL_ID` FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `software_article`
--
ALTER TABLE `software_article`
  ADD CONSTRAINT `FK_SOFTWARE_ARTICLE_SOFTWARE_ID` FOREIGN KEY (`SOFTWARE_ID`) REFERENCES `software` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_SOFTWARE_ARTICLE_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `software_demand`
--
ALTER TABLE `software_demand`
  ADD CONSTRAINT `FK_SOFTWARE_DEMAND_SOFTWARE_ID` FOREIGN KEY (`SOFTWARE_ID`) REFERENCES `software` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_SOFTWARE_DEMAND_DEMAND_ID` FOREIGN KEY (`DEMAND_ID`) REFERENCES `demand` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `stock_selection`
--
ALTER TABLE `stock_selection`
  ADD CONSTRAINT `FK_STOCK_SELECTION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
  
--
-- Constraints for table `stock_selection_types`
--
ALTER TABLE `stock_selection_types`
  ADD CONSTRAINT `FK_STOCK_SELECTION_TYPES_STOCKSELECTION_ID` FOREIGN KEY (`STOCKSELECTION_ID`) REFERENCES `stock_selection` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_STOCK_SELECTION_TYPES_TYPEARTICLE_ID` FOREIGN KEY (`TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `switch`
--
ALTER TABLE `switch`
  ADD CONSTRAINT `FK_SWITCH_ID` FOREIGN KEY (`ID`) REFERENCES `rack` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `tool`
--
ALTER TABLE `tool`
  ADD CONSTRAINT `FK_TOOL_COMMENT_ID` FOREIGN KEY (`COMMENT_ID`) REFERENCES `comment` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_TOOL_INSTALLATION_ID` FOREIGN KEY (`INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `typearticle_airbuspn`
--
ALTER TABLE `typearticle_airbuspn`
  ADD CONSTRAINT `FK_TYPEARTICLE_AIRBUSPN_TYPEARTICLE_ID` FOREIGN KEY (`TYPEARTICLE_ID`) REFERENCES `typearticle` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_TYPEARTICLE_AIRBUSPN_AIRBUSPN_ID` FOREIGN KEY (`AIRBUSPN_ID`) REFERENCES `airbuspn` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `user`
--
ALTER TABLE `user`
  ADD CONSTRAINT `FK_USER_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Constraints for table `various`
--
ALTER TABLE `various`
  ADD CONSTRAINT `FK_VARIOUS_ID` FOREIGN KEY (`ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
