--
-- UPDATE BOA DATABASE FROM VERSION 4.0 TO VERSION 4.1
--

-- UPDATE BOA DATABASE FOR BOA-DM-241
-- ADD TABLES departmentincharge AND ALTER TABLE pc
CREATE TABLE IF NOT EXISTS `departmentincharge` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODIFIABLE` tinyint(1) DEFAULT 0,
  `DELETABLE` tinyint(1) DEFAULT 0,
  `DEFAULTVALUE` varchar(10) DEFAULT NULL,
  `DESCRIPTION` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_DEPARTMENTINCHARGE_VALUE` (`DEFAULTVALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO departmentincharge (MODIFIABLE, DELETABLE, DEFAULTVALUE, DESCRIPTION)
VALUES (1, 1, 'EYYS', 'Modelling and Simulation'),(1, 1, 'EV','Flight and Integration Tests');

ALTER TABLE pc
 ADD DEPARTMENTINCHARGE_ID bigint(20) DEFAULT 1 AFTER NAME,
 ADD CONSTRAINT `FK_DEPARTMENTINCHARGE_ID` FOREIGN KEY (`DEPARTMENTINCHARGE_ID`) REFERENCES `departmentincharge` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- UPDATE BOA DATABASE FOR BOA-DM-250
-- ALTER TABLES aircraftprogram AND domain
ALTER TABLE aircraftprogram
 CHANGE VALUE DEFAULTVALUE varchar(30),
 ADD MODIFIABLE tinyint(1) DEFAULT 0 AFTER ID,
 ADD DELETABLE tinyint(1) DEFAULT 0 AFTER ID;

UPDATE aircraftprogram SET MODIFIABLE = 1, DELETABLE = 1;

ALTER TABLE domain
 CHANGE VALUE DEFAULTVALUE varchar(30),
 ADD MODIFIABLE tinyint(1) DEFAULT 0 AFTER ID,
 ADD DELETABLE tinyint(1) DEFAULT 0 AFTER ID;

UPDATE domain SET MODIFIABLE = 1, DELETABLE = 1;

-- UPDATE BOA DATABASE FOR BOA-DM-238
-- CLEAN fieldmodification VALUES
UPDATE fieldmodification SET AFTERVALUE = "" WHERE AFTERVALUE = "null";
UPDATE fieldmodification SET BEFOREVALUE = "" WHERE BEFOREVALUE = "null";
