--
-- UPDATE BOA DATABASE FROM VERSION 2.6 TO VERSION 3.0
--

-- UPDATE BOA DATABASE FOR BOA-DM-74

-- CHANGE UNIQUE KEY ON NAME COLUMN TO A UNIQUE KEY ON NAME AND BUILDING_ID COLUMNS OF place TABLE

ALTER TABLE place
 DROP KEY UK_PLACE_NAME,
 ADD UNIQUE KEY UK_PLACE_NAME_BUILDING (NAME, BUILDING_ID);

-- Update most of the existing places with a name compliant with the new place management

-- remove "Labo" and "Reserve"
UPDATE place
 SET place.NAME = REPLACE(place.NAME, "Labo ", "")
 WHERE place.NAME LIKE "Labo %"
 AND place.TYPE = "Laboratory";
UPDATE place
 SET place.NAME = REPLACE(place.NAME, "Reserve ", "")
 WHERE place.NAME LIKE "Reserve %"
 AND place.TYPE = "Storeroom";

-- remove the building name at the beginning of the place name (followed by '-', ' - ' or ' ')
UPDATE place
 JOIN building ON building.ID = place.BUILDING_ID
 SET place.NAME = REPLACE(place.NAME, CONCAT(building.NAME, "-"), "")
 WHERE place.NAME LIKE CONCAT(building.NAME, "-%");
UPDATE place
 JOIN building ON building.ID = place.BUILDING_ID
 SET place.NAME = REPLACE(place.NAME, CONCAT(building.NAME, " - "), "")
 WHERE place.NAME LIKE CONCAT(building.NAME, " - %");
UPDATE place
 JOIN building ON building.ID = place.BUILDING_ID
 SET place.NAME = REPLACE(place.NAME, CONCAT(building.NAME, " "), "")
 WHERE place.NAME LIKE CONCAT(building.NAME, " %");


-- UPDATE BOA DATABASE FOR BOA-DM-114

-- CHANGE THE PASSWORD COLUMN SIZE OF user TABLE

ALTER TABLE user
 CHANGE PASSWORD PASSWORD varchar(32) DEFAULT NULL;

-- UPDATE THE PASSWORD COLUMN CONTENT OF user TABLE

UPDATE user
 SET PASSWORD = MD5(PASSWORD);


-- UPDATE BOA DATABASE FOR BOA-DM-138

-- CREATE THE reminder TABLE

CREATE TABLE IF NOT EXISTS `reminder` (
  `ID` bigint(20) NOT NULL,
  `TARGETDATE` date NOT NULL,
  `NBDAYSNOTIFICATION` int(11) NOT NULL,
  `ARTICLE_ID` bigint(20) DEFAULT NULL,
  `INSTALLATION_ID` bigint(20) DEFAULT NULL,
  `TOOL_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `OBJECT` varchar(254) NOT NULL,
  `COMPLETED` tinyint(4) NOT NULL DEFAULT '0',
  `REMINDERSTATUS` varchar(15) NOT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `K_REMINDER_USER_ID` (`USER_ID`),
  KEY `K_REMINDER_ARTICLE_ID` (`ARTICLE_ID`),
  CONSTRAINT `FK_REMINDER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_REMINDER_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `article` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_REMINDER_INSTALLATION_ID` FOREIGN KEY (`INSTALLATION_ID`) REFERENCES `installation` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_REMINDER_TOOL_ID` FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- UPDATE BOA DATABASE FOR BOA-DM-136

-- ADD AUTOUPDATE COLUMN  AND UNIQUE CONSTRAINT ON NAME COLUMN ON pc TABLE

ALTER TABLE pc
 ADD `AUTOUPDATE` tinyint(1) DEFAULT '0',
 ADD UNIQUE KEY `UK_PC_NAME` (`NAME`);

