--
-- UPDATE BOA DATABASE FROM VERSION 2.3 TO VERSION 2.4
--

-- UPDATE BOA DATABASE FOR BOA-DM-84

-- CHANGE THE NAME COLUMN SIZE IN THE INSTALLATION TABLE

ALTER TABLE INSTALLATION
 CHANGE NAME NAME VARCHAR(50) NOT NULL;


-- UPDATE BOA DATABASE FOR BOA-DM-64

-- RENAME THE DESIGNATION COLUMN TO COMMENT IN THE INSTALLATION TABLE

ALTER TABLE INSTALLATION
 CHANGE DESIGNATION COMMENTS VARCHAR(50) DEFAULT NULL;


-- UPDATE BOA DATABASE FOR BOA-DM-77

-- RENAME THE TYPE_ID COLUMN TO PRODUCTTYPEPC_ID IN THE PC TABLE

ALTER TABLE PC
 CHANGE TYPE_ID PRODUCTTYPEPC_ID BIGINT(20) DEFAULT NULL;

-- RENAME THE ModelPC CLASS TO TypePC (UPDATE DTYPE COLUMN IN THE TYPEARTICLE TABLE)

UPDATE TYPEARTICLE
 SET DTYPE = 'TypePC' WHERE DTYPE = 'ModelPC';

-- RENAME THE MODELEPC_ID COLUMN TO TYPEPC_TYPEARTICLE_ID IN THE OBSOLESCENCEDATA TABLE

ALTER TABLE OBSOLESCENCEDATA
 CHANGE MODELEPC_ID TYPEPC_TYPEARTICLE_ID BIGINT( 20 ) DEFAULT NULL;

-- RENAME THE "model" FIELD TO "TypeArticle" IN THE FIELDMODIFICATION TABLE

UPDATE FIELDMODIFICATION
 SET FIELD = 'TypeArticle' WHERE FIELD = 'model';

-- RENAME THE "type" FIELD TO "ProductType" IN THE FIELDMODIFICATION TABLE

UPDATE FIELDMODIFICATION
 SET FIELD = 'ProductType' WHERE FIELD = 'type';


-- UPDATE BOA DATABASE FOR BOA-DM-80

-- RENAME THE "REBUT" BUILDING AND PLACE TO "REBUT (SCRAP)"

UPDATE BUILDING
 SET NAME = 'REBUT (SCRAP)' WHERE NAME = 'REBUT';

UPDATE PLACE
 SET NAME = 'REBUT (SCRAP)' WHERE NAME = 'REBUT';


-- UPDATE BOA DATABASE FOR BOA-DM-62

-- ADD COMMENTS INTO COMMUNICATIONPORT TABLE 

ALTER TABLE COMMUNICATIONPORT
 ADD COMMENTS VARCHAR( 200 ) NULL DEFAULT NULL;


-- UPDATE BOA DATABASE FOR BOA-DM-90

-- UPDATE THE MESSAGE COLUMN IN COMMENT TABLE (CHANGE THE CREATION MESSAGES FROM FRENCH TO ENGLISH)

UPDATE COMMENT
 SET MESSAGE = 'Created by HMI' WHERE MESSAGE = 'Création par l\'interface'; -- \'

UPDATE COMMENT
 SET MESSAGE = 'Created by Import' WHERE MESSAGE = 'Création par importation';

-- UPDATE THE MESSAGE COLUMN IN COMMENT TABLE (CHANGE THE COMMUNICATION PORT NAME FROM FRENCH TO ENGLISH)

UPDATE COMMENT
 SET MESSAGE = REPLACE(MESSAGE, 'Nom:', 'Name:') WHERE MESSAGE LIKE 'Nom:%';

-- UPDATE THE BEFOREVALUE AND AFTERVALUE COLUMNS IN FIELDMODIFICATION TABLE
-- (CHANGE THE STATE FROM FRENCH TO ENGLISH)

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = 'On Purchase' WHERE BEFOREVALUE = 'En cours de commande' AND FIELD = 'State';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = 'On Purchase' WHERE AFTERVALUE = 'En cours de commande' AND FIELD = 'State';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = 'Operational' WHERE BEFOREVALUE = 'En service' AND FIELD = 'State';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = 'Operational' WHERE AFTERVALUE = 'En service' AND FIELD = 'State';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = 'Out of Order' WHERE BEFOREVALUE = 'Hors Service' AND FIELD = 'State';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = 'Out of Order' WHERE AFTERVALUE = 'Hors Service' AND FIELD = 'State';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = 'Retrofit' WHERE BEFOREVALUE = 'Rétrofit' AND FIELD = 'State';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = 'Retrofit' WHERE AFTERVALUE = 'Rétrofit' AND FIELD = 'State';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = 'Unknown' WHERE BEFOREVALUE = 'Inconnu' AND FIELD = 'State';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = 'Unknown' WHERE AFTERVALUE = 'Inconnu' AND FIELD = 'State';

-- UPDATE THE BEFOREVALUE AND AFTERVALUE COLUMNS IN FIELDMODIFICATION TABLE
-- (CHANGE THE LOCATION DESCRIPTION FROM FRENCH TO ENGLISH)

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, ' :', ':'),
     AFTERVALUE = REPLACE(AFTERVALUE, ' :', ':')
 WHERE FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Carte mère:', 'Motherboard:') WHERE BEFOREVALUE LIKE 'Carte mère:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'carte mère:', 'Motherboard:') WHERE BEFOREVALUE LIKE 'Carte mère:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Carte mère:', 'Motherboard:') WHERE AFTERVALUE LIKE 'Carte mère:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'carte mère:', 'Motherboard:') WHERE AFTERVALUE LIKE 'Carte mère:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Baie:', 'Cabinet:') WHERE BEFOREVALUE LIKE 'Baie:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'baie:', 'Cabinet:') WHERE BEFOREVALUE LIKE 'Baie:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Baie:', 'Cabinet:') WHERE AFTERVALUE LIKE 'Baie:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'baie:', 'Cabinet:') WHERE AFTERVALUE LIKE 'Baie:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'installation:', 'Installation:') WHERE BEFOREVALUE LIKE 'Installation:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'installation:', 'Installation:') WHERE AFTERVALUE LIKE 'Installation:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Emplacement:', 'Place:') WHERE BEFOREVALUE LIKE 'Emplacement:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'emplacement:', 'Place:') WHERE BEFOREVALUE LIKE 'Emplacement:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Emplacement:', 'Place:') WHERE AFTERVALUE LIKE 'Emplacement:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'emplacement:', 'Place:') WHERE AFTERVALUE LIKE 'Emplacement:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'rack:', 'Rack:') WHERE BEFOREVALUE LIKE 'Rack:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'rack:', 'Rack:') WHERE AFTERVALUE LIKE 'Rack:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Fournisseur:', 'Supplier:') WHERE BEFOREVALUE LIKE 'Fournisseur:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'fournisseur:', 'Supplier:') WHERE BEFOREVALUE LIKE 'Fournisseur:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Fournisseur:', 'Supplier:') WHERE AFTERVALUE LIKE 'Fournisseur:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'fournisseur:', 'Supplier:') WHERE AFTERVALUE LIKE 'Fournisseur:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'switch:', 'Switch:') WHERE BEFOREVALUE LIKE 'Switch:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'switch:', 'Switch:') WHERE AFTERVALUE LIKE 'Switch:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Outil:', 'Tool:') WHERE BEFOREVALUE LIKE 'Outil:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Outil:', 'Tool:') WHERE AFTERVALUE LIKE 'Outil:%' AND FIELD = 'Localisation';

UPDATE FIELDMODIFICATION
 SET BEFOREVALUE = REPLACE(BEFOREVALUE, 'Position:', 'Details:') WHERE BEFOREVALUE LIKE '%Position:%' AND FIELD = 'Localisation';
UPDATE FIELDMODIFICATION
 SET AFTERVALUE = REPLACE(AFTERVALUE, 'Position:', 'Details:') WHERE AFTERVALUE LIKE '%Position:%' AND FIELD = 'Localisation';


-- UPDATE BOA DATABASE FOR BOA-DM-56

-- ADD THE TYPE ARTICLE COLUMN IN OBSOLESCENCEDATA TABLE
-- UPDATE THE INDEXES (REPLACE THE UNIQUE INDEXES ON PN BY UNIQUE INDEXES ON PN AND TYPEARTICLE)

ALTER TABLE OBSOLESCENCEDATA
 ADD TYPEARTICLE_ID BIGINT NULL DEFAULT NULL AFTER APN_ID,
 DROP INDEX APN_ID,
 DROP INDEX MPN_ID,
 ADD UNIQUE UK_OBSOLESCENCEDATA_APN_ID_TYPEARTICLE_ID (APN_ID, TYPEARTICLE_ID),
 ADD UNIQUE UK_OBSOLESCENCEDATA_MPN_ID_TYPEARTICLE_ID (MPN_ID, TYPEARTICLE_ID);

-- UPDATE THE TYPEARTICLE_ID COLUMN IN OBSOLESCENCEDATA TABLE WITH THE UNIQUE TYPE ARTICLE FOUND

CREATE VIEW view_OBSO_EMPTY_TYPEARTICLE AS
SELECT DISTINCT APN_ID AS OBSO_APN_ID, MPN_ID AS OBSO_MPN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID AS OBSO_TYPE_ID,
 ARTICLE.AIRBUSPN_ID AS ART_APN_ID, ARTICLE.MANUFACTURERPN_ID AS ART_MPN_ID,
 TYPEARTICLE.ID AS TYPE_ID, TYPEARTICLE.LABEL AS TYPE_LABEL,
 TYPEARTICLE_AIRBUSPN.TYPEARTICLE_ID AS TYPE_APN_ASSO_TYPE_ID,
 COUNT(OBSOLESCENCEDATA.ID) AS NB
FROM OBSOLESCENCEDATA
LEFT JOIN ARTICLE ON (ARTICLE.AIRBUSPN_ID = OBSOLESCENCEDATA.APN_ID OR ARTICLE.MANUFACTURERPN_ID = OBSOLESCENCEDATA.MPN_ID)
LEFT JOIN TYPEARTICLE ON TYPEARTICLE.ID = ARTICLE.TYPE_FK
LEFT JOIN TYPEARTICLE_AIRBUSPN ON TYPEARTICLE_AIRBUSPN.AIRBUSPN_ID = OBSOLESCENCEDATA.APN_ID
WHERE (APN_ID IS NOT NULL OR MPN_ID IS NOT NULL)
 AND OBSOLESCENCEDATA.TYPEARTICLE_ID IS NULL
GROUP BY APN_ID, MPN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID,
 ARTICLE.AIRBUSPN_ID, ARTICLE.MANUFACTURERPN_ID,
 TYPEARTICLE.ID,
 TYPEARTICLE_AIRBUSPN.TYPEARTICLE_ID
ORDER BY APN_ID, MPN_ID;

CREATE VIEW view_OBSO_APN AS
SELECT APN_ID AS OBSO_APN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID AS OBSO_TYPE_ID,
 ARTICLE.AIRBUSPN_ID AS ART_APN_ID,
 TYPEARTICLE.ID AS TYPE_ID,
 TYPEARTICLE_AIRBUSPN.TYPEARTICLE_ID AS TYPE_APN_ASSO_TYPE_ID,
 COUNT(DISTINCT TYPEARTICLE_AIRBUSPN.TYPEARTICLE_ID) AS NB_TYPES
FROM OBSOLESCENCEDATA
LEFT JOIN ARTICLE ON ARTICLE.AIRBUSPN_ID = OBSOLESCENCEDATA.APN_ID
LEFT JOIN TYPEARTICLE ON TYPEARTICLE.ID = ARTICLE.TYPE_FK
LEFT JOIN TYPEARTICLE_AIRBUSPN ON TYPEARTICLE_AIRBUSPN.AIRBUSPN_ID = OBSOLESCENCEDATA.APN_ID
WHERE APN_ID IS NOT NULL
GROUP BY APN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID,
 ARTICLE.AIRBUSPN_ID,
 TYPEARTICLE.ID
ORDER BY APN_ID;

CREATE VIEW view_OBSO_MPN AS
SELECT MPN_ID AS OBSO_MPN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID AS OBSO_TYPE_ID,
 ARTICLE.MANUFACTURERPN_ID AS ART_MPN_ID,
 TYPEARTICLE.ID AS FIRST_TYPE_ID,
 COUNT(DISTINCT TYPEARTICLE.ID) AS NB_TYPES
FROM OBSOLESCENCEDATA
LEFT JOIN ARTICLE ON ARTICLE.MANUFACTURERPN_ID = OBSOLESCENCEDATA.MPN_ID
LEFT JOIN TYPEARTICLE ON TYPEARTICLE.ID = ARTICLE.TYPE_FK
WHERE MPN_ID IS NOT NULL
GROUP BY MPN_ID, OBSOLESCENCEDATA.TYPEARTICLE_ID
ORDER BY MPN_ID;

-- UPDATE THE TYPEARTICLE_ID COLUMN FOR AIRBUS PN OBSOLESCENCE DATA
UPDATE OBSOLESCENCEDATA
 SET TYPEARTICLE_ID = (SELECT TYPE_APN_ASSO_TYPE_ID
                       FROM view_OBSO_APN
                       WHERE view_OBSO_APN.OBSO_APN_ID = OBSOLESCENCEDATA.APN_ID
                        AND view_OBSO_APN.NB_TYPES = 1)
 WHERE APN_ID IS NOT NULL
  AND TYPEARTICLE_ID IS NULL;

-- UPDATE THE TYPEARTICLE_ID COLUMN FOR MANUFACTURER PN OBSOLESCENCE DATA
UPDATE OBSOLESCENCEDATA
 SET TYPEARTICLE_ID = (SELECT FIRST_TYPE_ID
                       FROM view_OBSO_MPN
                       WHERE view_OBSO_MPN.OBSO_MPN_ID = OBSOLESCENCEDATA.MPN_ID
                        AND view_OBSO_MPN.NB_TYPES = 1)
 WHERE MPN_ID IS NOT NULL
  AND TYPEARTICLE_ID IS NULL;

-- => Treat manually remaining Obsolescence Data on Airbus or Manufacturer PN but without associated Type Article

DROP VIEW view_OBSO_EMPTY_TYPEARTICLE;
DROP VIEW view_OBSO_APN;
DROP VIEW view_OBSO_MPN;


-- UPDATE BOA DATABASE FOR BOA-DM-8

-- DELETE UNUSED TABLES

DROP TABLE ATTRIBUTEVALUELIST;
DROP TABLE ATTRIBUTEVALUELIST_TRANSLATION;
DROP TABLE PN;

-- UPDATE ENGINE TO INNODB FOR ALL TABLES

ALTER TABLE ACTION ENGINE=INNODB;
ALTER TABLE ACTIONOBSO ENGINE=INNODB;
ALTER TABLE ACTIONOBSO_TRANSLATION ENGINE=INNODB;
ALTER TABLE AIRBUSPN ENGINE=INNODB;
ALTER TABLE AIRBUSSTATUS ENGINE=INNODB;
ALTER TABLE AIRBUSSTATUS_TRANSLATION ENGINE=INNODB;
ALTER TABLE ARTICLE ENGINE=INNODB;
ALTER TABLE BOARD ENGINE=INNODB;
ALTER TABLE BOARD_COMMUNICATIONPORT ENGINE=INNODB;
ALTER TABLE BUILDING ENGINE=INNODB;
ALTER TABLE BUSINESSALLOCATIONPC ENGINE=INNODB;
ALTER TABLE BUSINESSALLOCATIONPC_TRANSLATION ENGINE=INNODB;
ALTER TABLE BUSINESSUSAGEPC ENGINE=INNODB;
ALTER TABLE BUSINESSUSAGEPC_TRANSLATION ENGINE=INNODB;
ALTER TABLE CABINET ENGINE=INNODB;
ALTER TABLE COMMENT ENGINE=INNODB;
ALTER TABLE COMMUNICATIONPORT ENGINE=INNODB;
ALTER TABLE CONSULTPERIOD ENGINE=INNODB;
ALTER TABLE CONSULTPERIOD_TRANSLATION ENGINE=INNODB;
ALTER TABLE CONTAINS_CABINET_RACK ENGINE=INNODB;
ALTER TABLE CONTAINS_INST_CABINET ENGINE=INNODB;
ALTER TABLE CONTAINS_PC_BOARD ENGINE=INNODB;
ALTER TABLE CONTAINS_PLACE_TOOL ENGINE=INNODB;
ALTER TABLE CONTAINS_RACK_BOARD ENGINE=INNODB;
ALTER TABLE CONTAINS_TOOL_ARTICLE ENGINE=INNODB;
ALTER TABLE FIELDMODIFICATION ENGINE=INNODB;
ALTER TABLE HISTORY ENGINE=INNODB;
ALTER TABLE INSTALLATION ENGINE=INNODB;
ALTER TABLE MANUFACTURERPN ENGINE=INNODB;
ALTER TABLE MANUFACTURERSTATUS ENGINE=INNODB;
ALTER TABLE MANUFACTURERSTATUS_TRANSLATION ENGINE=INNODB;
ALTER TABLE NESTEDSET ENGINE=INNODB;
ALTER TABLE NETWORK ENGINE=INNODB;
ALTER TABLE NETWORK_TRANSLATION ENGINE=INNODB;
ALTER TABLE OBSOLESCENCEDATA ENGINE=INNODB;
ALTER TABLE PC ENGINE=INNODB;
ALTER TABLE PC_COMMUNICATIONPORT ENGINE=INNODB;
ALTER TABLE PLACE ENGINE=INNODB;
ALTER TABLE PLACE_STORERELATION ENGINE=INNODB;
ALTER TABLE PRODUCTTYPEPC ENGINE=INNODB;
ALTER TABLE PRODUCTTYPEPC_TRANSLATION ENGINE=INNODB;
ALTER TABLE RACK ENGINE=INNODB;
ALTER TABLE ROLE ENGINE=INNODB;
ALTER TABLE SEQUENCE ENGINE=INNODB;
ALTER TABLE SERVICE ENGINE=INNODB;
ALTER TABLE SOFTWARE ENGINE=INNODB;
ALTER TABLE SOFTWARE_ARTICLE ENGINE=INNODB;
ALTER TABLE STORERELATION ENGINE=INNODB;
ALTER TABLE STRATEGY ENGINE=INNODB;
ALTER TABLE STRATEGY_TRANSLATION ENGINE=INNODB;
ALTER TABLE SUPPLIER ENGINE=INNODB;
ALTER TABLE SWITCH ENGINE=INNODB;
ALTER TABLE TOOL ENGINE=INNODB;
ALTER TABLE TRANSLATION ENGINE=INNODB;
ALTER TABLE TYPEARTICLE ENGINE=INNODB;
ALTER TABLE TYPEARTICLE_AIRBUSPN ENGINE=INNODB;
ALTER TABLE USER ENGINE=INNODB;
ALTER TABLE USER_ROLES ENGINE=INNODB;
ALTER TABLE VARIOUS ENGINE=INNODB;

-- UPDATE TABLES NAME

RENAME TABLE USER_ROLES TO USER_ROLE;

-- UPDATE COLUMNS CHARACTERISTICS

ALTER TABLE SWITCH
 CHANGE IPADDRESS IPADDRESS VARCHAR (39) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;

-- UPDATE TABLES (COLUMNS NAMES AND CORRESPONDING INDEXES NAMES, FOREIGN KEYS)

ALTER TABLE ACTION
 DROP INDEX FK_ACTION_COMMENT_FK,
 DROP INDEX FK_ACTION_HISTORY_FK,
 CHANGE COMMENT_FK COMMENT_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE HISTORY_FK HISTORY_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_ACTION_COMMENT_ID (COMMENT_ID),
 ADD INDEX K_ACTION_HISTORY_ID (HISTORY_ID),
 ADD CONSTRAINT FK_ACTION_COMMENT_ID FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ACTION_HISTORY_ID FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ACTIONOBSO_TRANSLATION
 DROP INDEX FK_ACTIONOBSO_TRANSLATION_translations_ID,
 CHANGE ActionObso_ID ACTIONOBSO_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_ACTIONOBSO_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_ACTIONOBSO_TRANSLATION_ACTIONOBSO_ID FOREIGN KEY (ACTIONOBSO_ID) REFERENCES ACTIONOBSO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ACTIONOBSO_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE AIRBUSPN
 DROP INDEX IDENTIFIER,
 ADD UNIQUE UK_AIRBUSPN_IDENTIFIER (IDENTIFIER);

ALTER TABLE AIRBUSSTATUS_TRANSLATION
 DROP INDEX FK_AIRBUSSTATUS_TRANSLATION_translations_ID,
 CHANGE AirbusStatus_ID AIRBUSSTATUS_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_AIRBUSSTATUS_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_AIRBUSSTATUS_TRANSLATION_AIRBUSSTATUS_ID FOREIGN KEY (AIRBUSSTATUS_ID) REFERENCES AIRBUSSTATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_AIRBUSSTATUS_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ARTICLE
 DROP INDEX AIRBUSSN,
 DROP INDEX FK_ARTICLE_HISTORY,
 DROP INDEX FK_ARTICLE_USEDBYINSTALLATION_ID,
 DROP INDEX FK_ARTICLE_LENTTO_ID,
 DROP INDEX FK_ARTICLE_USEDBY_ID,
 DROP INDEX FK_ARTICLE_SENTTO_ID,
 DROP INDEX FK_ARTICLE_DEDICATEDTO,
 DROP INDEX FK_ARTICLE_TYPE_FK,
 DROP INDEX FK_ARTICLE_MANUFACTURERPN_ID,
 DROP INDEX FK_ARTICLE_AIRBUSPN_ID,
 CHANGE HISTORY HISTORY_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE USEDBYINSTALLATION_ID USEDBY_INSTALLATION_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE SENTTO_ID SENTTO_SUPPLIER_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE DEDICATEDTO DEDICATEDTO_INSTALLATION_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE TYPE_FK TYPEARTICLE_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE USEDBY_ID USEDBY_ARTICLE_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE LENTTO_ID LENTTO_SERVICE_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_ARTICLE_HISTORY_ID (HISTORY_ID),
 ADD INDEX K_ARTICLE_USEDBY_INSTALLATION_ID (USEDBY_INSTALLATION_ID),
 ADD INDEX K_ARTICLE_LENTTO_SERVICE_ID (LENTTO_SERVICE_ID),
 ADD INDEX K_ARTICLE_USEDBY_ARTICLE_ID (USEDBY_ARTICLE_ID),
 ADD INDEX K_ARTICLE_MANUFACTURERPN_ID (MANUFACTURERPN_ID),
 ADD INDEX K_ARTICLE_AIRBUSPN_ID (AIRBUSPN_ID),
 ADD INDEX K_ARTICLE_SENTTO_SUPPLIER_ID (SENTTO_SUPPLIER_ID),
 ADD INDEX K_ARTICLE_DEDICATEDTO_INSTALLATION_ID (DEDICATEDTO_INSTALLATION_ID),
 ADD INDEX K_ARTICLE_TYPEARTICLE_ID (TYPEARTICLE_ID),
 ADD UNIQUE UK_ARTICLE_AIRBUSSN (AIRBUSSN),
 ADD CONSTRAINT FK_ARTICLE_USEDBY_INSTALLATION_ID FOREIGN KEY (USEDBY_INSTALLATION_ID) REFERENCES INSTALLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_SENTTO_SUPPLIER_ID FOREIGN KEY (SENTTO_SUPPLIER_ID) REFERENCES SUPPLIER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_MANUFACTURERPN_ID FOREIGN KEY (MANUFACTURERPN_ID) REFERENCES MANUFACTURERPN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_DEDICATEDTO_INSTALLATION_ID FOREIGN KEY (DEDICATEDTO_INSTALLATION_ID) REFERENCES INSTALLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_TYPEARTICLE_ID FOREIGN KEY (TYPEARTICLE_ID) REFERENCES TYPEARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_AIRBUSPN_ID FOREIGN KEY (AIRBUSPN_ID) REFERENCES AIRBUSPN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_USEDBY_ARTICLE_ID FOREIGN KEY (USEDBY_ARTICLE_ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_HISTORY_ID FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_ARTICLE_LENTTO_SERVICE_ID FOREIGN KEY (LENTTO_SERVICE_ID) REFERENCES SERVICE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE BOARD
 ADD CONSTRAINT FK_BOARD_ID FOREIGN KEY (ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE BOARD_COMMUNICATIONPORT
 DROP INDEX FK_BOARD_COMMUNICATIONPORT_ports_ID,
 CHANGE Board_ID BOARD_ID BIGINT(20) NOT NULL,
 CHANGE ports_ID COMMUNICATIONPORT_ID BIGINT(20) NOT NULL,
 ADD INDEX K_BOARD_COMMUNICATIONPORT_COMMUNICATIONPORT_ID (COMMUNICATIONPORT_ID),
 ADD CONSTRAINT FK_BOARD_COMMUNICATIONPORT_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_BOARD_COMMUNICATIONPORT_COMMUNICATIONPORT_ID FOREIGN KEY (COMMUNICATIONPORT_ID) REFERENCES COMMUNICATIONPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE BUILDING
 DROP INDEX NAME,
 ADD UNIQUE UK_BUILDING_NAME (NAME);

ALTER TABLE BUSINESSALLOCATIONPC_TRANSLATION
 DROP INDEX BUSINESSALLOCATIONPC_TRANSLATION_translations_ID,
 CHANGE BusinessAllocationPC_ID BUSINESSALLOCATIONPC_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_BUSINESSALLOCATIONPC_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_BUSINESSALLOCATIONPC_TRANSLATION_BUSINESSALLOCATIONPC_ID FOREIGN KEY (BUSINESSALLOCATIONPC_ID) REFERENCES BUSINESSALLOCATIONPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_BUSINESSALLOCATIONPC_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE BUSINESSUSAGEPC_TRANSLATION
 DROP INDEX FK_BUSINESSUSAGEPC_TRANSLATION_translations_ID,
 CHANGE BusinessUsagePC_ID BUSINESSUSAGEPC_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_BUSINESSUSAGEPC_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_BUSINESSUSAGEPC_TRANSLATION_BUSINESSUSAGEPC_ID FOREIGN KEY (BUSINESSUSAGEPC_ID) REFERENCES BUSINESSUSAGEPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_BUSINESSUSAGEPC_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CABINET
 DROP INDEX DESIGNATION,
 ADD UNIQUE UK_CABINET_DESIGNATION (DESIGNATION),
 ADD CONSTRAINT FK_CABINET_ID FOREIGN KEY (ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE COMMUNICATIONPORT
 DROP INDEX FK_COMMUNICATIONPORT_NETWORK_ID,
 ADD INDEX K_COMMUNICATIONPORT_NETWORK_ID (NETWORK_ID),
 ADD CONSTRAINT FK_COMMUNICATIONPORT_NETWORK_ID FOREIGN KEY (NETWORK_ID) REFERENCES NETWORK (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONSULTPERIOD_TRANSLATION
 DROP INDEX FK_CONSULTPERIOD_TRANSLATION_translations_ID,
 CHANGE ConsultPeriod_ID CONSULTPERIOD_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_CONSULTPERIOD_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_CONSULTPERIOD_TRANSLATION_CONSULTPERIOD_ID FOREIGN KEY (CONSULTPERIOD_ID) REFERENCES CONSULTPERIOD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONSULTPERIOD_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_CABINET_RACK
 DROP INDEX FK_CONTAINS_CABINET_RACK_RACK_FK,
 DROP INDEX FK_CONTAINS_CABINET_RACK_CABINET_FK,
 CHANGE RACK_FK RACK_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE CABINET_FK CABINET_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_CABINET_RACK_CABINET_ID (CABINET_ID),
 ADD INDEX K_CONTAINS_CABINET_RACK_RACK_ID (RACK_ID),
 ADD CONSTRAINT FK_CONTAINS_CABINET_RACK_RACK_ID FOREIGN KEY (RACK_ID) REFERENCES RACK (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_CABINET_RACK_CABINET_ID FOREIGN KEY (CABINET_ID) REFERENCES CABINET (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_INST_CABINET
 DROP INDEX FK_CONTAINS_INST_CABINET_INSTALLATION_FK,
 DROP INDEX FK_CONTAINS_INST_CABINET_CABINET_FK,
 CHANGE CABINET_FK CABINET_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE INSTALLATION_FK INSTALLATION_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_INST_CABINET_INSTALLATION_ID (INSTALLATION_ID),
 ADD INDEX K_CONTAINS_INST_CABINET_CABINET_ID (CABINET_ID),
 ADD CONSTRAINT FK_CONTAINS_INST_CABINET_INSTALLATION_ID FOREIGN KEY (INSTALLATION_ID) REFERENCES INSTALLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_INST_CABINET_CABINET_ID FOREIGN KEY (CABINET_ID) REFERENCES CABINET (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_PC_BOARD
 DROP INDEX FK_CONTAINS_PC_BOARD_BOARD_FK,
 DROP INDEX FK_CONTAINS_PC_BOARD_PC_FK,
 CHANGE BOARD_FK BOARD_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE PC_FK PC_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_PC_BOARD_BOARD_ID (BOARD_ID),
 ADD INDEX K_CONTAINS_PC_BOARD_PC_ID (PC_ID),
 ADD CONSTRAINT FK_CONTAINS_PC_BOARD_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_PC_BOARD_PC_ID FOREIGN KEY (PC_ID) REFERENCES PC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_PLACE_TOOL
 DROP INDEX FK_CONTAINS_PLACE_TOOL_PLACE_FK,
 DROP INDEX FK_CONTAINS_PLACE_TOOL_TOOL_FK,
 CHANGE PLACE_FK PLACE_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE TOOL_FK TOOL_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_PLACE_TOOL_PLACE_ID (PLACE_ID),
 ADD INDEX K_CONTAINS_PLACE_TOOL_TOOL_ID (TOOL_ID),
 ADD CONSTRAINT FK_CONTAINS_PLACE_TOOL_PLACE_ID FOREIGN KEY (PLACE_ID) REFERENCES PLACE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_PLACE_TOOL_TOOL_ID FOREIGN KEY (TOOL_ID) REFERENCES TOOL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_RACK_BOARD
 DROP INDEX FK_CONTAINS_RACK_BOARD_BOARD_FK,
 DROP INDEX FK_CONTAINS_RACK_BOARD_RACK_FK,
 CHANGE BOARD_FK BOARD_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE RACK_FK RACK_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_RACK_BOARD_BOARD_ID (BOARD_ID),
 ADD INDEX K_CONTAINS_RACK_BOARD_RACK_ID (RACK_ID),
 ADD CONSTRAINT FK_CONTAINS_RACK_BOARD_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_RACK_BOARD_RACK_ID FOREIGN KEY (RACK_ID) REFERENCES RACK (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CONTAINS_TOOL_ARTICLE
 DROP INDEX FK_CONTAINS_TOOL_ARTICLE_TOOL_FK,
 DROP INDEX FK_CONTAINS_TOOL_ARTICLE_ARTICLE_FK,
 CHANGE TOOL_FK TOOL_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE ARTICLE_FK ARTICLE_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_CONTAINS_TOOL_ARTICLE_TOOL_ID (TOOL_ID),
 ADD INDEX K_CONTAINS_TOOL_ARTICLE_ARTICLE_ID (ARTICLE_ID),
 ADD CONSTRAINT FK_CONTAINS_TOOL_ARTICLE_TOOL_ID FOREIGN KEY (TOOL_ID) REFERENCES TOOL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_CONTAINS_TOOL_ARTICLE_ARTICLE_ID FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE FIELDMODIFICATION
 ADD CONSTRAINT FK_FIELDMODIFICATION_ID FOREIGN KEY (ID) REFERENCES ACTION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HISTORY
 DROP INDEX FK_HISTORY_GENERALCOMMENT_ID,
 CHANGE GENERALCOMMENT_ID GENERAL_COMMENT_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_HISTORY_GENERAL_COMMENT_ID (GENERAL_COMMENT_ID),
 ADD CONSTRAINT FK_HISTORY_GENERAL_COMMENT_ID FOREIGN KEY (GENERAL_COMMENT_ID) REFERENCES COMMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE INSTALLATION
 DROP INDEX FK_INSTALLATION_BUILDING_FK,
 DROP INDEX FK_INSTALLATION_LABO_FK,
 DROP INDEX FK_INSTALLATION_HISTORY_FK,
 DROP INDEX NAME,
 CHANGE BUILDING_FK BUILDING_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE HISTORY_FK HISTORY_ID BIGINT(20) NOT NULL,
 CHANGE LABO_FK LABO_PLACE_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_INSTALLATION_BUILDING_ID (BUILDING_ID),
 ADD INDEX K_INSTALLATION_LABO_PLACE_ID (LABO_PLACE_ID),
 ADD INDEX K_INSTALLATION_HISTORY_ID (HISTORY_ID),
 ADD UNIQUE UK_INSTALLATION_NAME (NAME),
 ADD CONSTRAINT FK_INSTALLATION_BUILDING_ID FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_INSTALLATION_HISTORY_ID FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_INSTALLATION_LABO_PLACE_ID FOREIGN KEY (LABO_PLACE_ID) REFERENCES PLACE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MANUFACTURERPN
 DROP INDEX IDENTIFIER,
 ADD UNIQUE UK_MANUFACTURERPN_IDENTIFIER (IDENTIFIER);

ALTER TABLE MANUFACTURERSTATUS_TRANSLATION
 DROP INDEX FK_MANUFACTURERSTATUS_TRANSLATION_translations_ID,
 CHANGE ManufacturerStatus_ID MANUFACTURERSTATUS_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_MANUFACTURERSTATUS_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_MANUFACTURERSTATUS_TRANSLATION_MANUFACTURERSTATUS_ID FOREIGN KEY (MANUFACTURERSTATUS_ID) REFERENCES MANUFACTURERSTATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_MANUFACTURERSTATUS_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE NESTEDSET
 DROP INDEX FK_NESTEDSET_SUPPLIER_ID,
 DROP INDEX FK_NESTEDSET_ARTICLE_ID,
 DROP INDEX FK_NESTEDSET_PLACE_ID,
 DROP INDEX FK_NESTEDSET_SERVICE_ID,
 DROP INDEX FK_NESTEDSET_INSTALLATION_ID,
 ADD INDEX K_NESTEDSET_SUPPLIER_ID (SUPPLIER_ID),
 ADD INDEX K_NESTEDSET_ARTICLE_ID (ARTICLE_ID),
 ADD INDEX K_NESTEDSET_PLACE_ID (PLACE_ID),
 ADD INDEX K_NESTEDSET_SERVICE_ID (SERVICE_ID),
 ADD INDEX K_NESTEDSET_INSTALLATION_ID (INSTALLATION_ID),
 ADD CONSTRAINT FK_NESTEDSET_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_NESTEDSET_INSTALLATION_ID FOREIGN KEY (INSTALLATION_ID) REFERENCES INSTALLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_NESTEDSET_PLACE_ID FOREIGN KEY (PLACE_ID) REFERENCES PLACE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_NESTEDSET_ARTICLE_ID FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_NESTEDSET_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE NETWORK_TRANSLATION
 DROP INDEX FK_NETWORK_TRANSLATION_translations_ID,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 CHANGE Network_ID NETWORK_ID BIGINT(20) NOT NULL,
 ADD INDEX K_NETWORK_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_NETWORK_TRANSLATION_NETWORK_ID FOREIGN KEY (NETWORK_ID) REFERENCES NETWORK (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_NETWORK_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OBSOLESCENCEDATA
 DROP INDEX FK_OBSOLESCENCEDATA_CURRENTACTION_ID,
 DROP INDEX FK_OBSOLESCENCEDATA_STRATEGYKEPT_ID,
 DROP INDEX FK_OBSOLESCENCEDATA_AIRBUSSTATUS_ID,
 DROP INDEX FK_OBSOLESCENCEDATA_MANUFACTURERSTATUS_ID,
 DROP INDEX FK_OBSOLESCENCEDATA_CONSULTPERIOD_ID,
 DROP INDEX UK_OBSOLESCENCEDATA_APN_ID_TYPEARTICLE_ID,
 DROP INDEX UK_OBSOLESCENCEDATA_MPN_ID_TYPEARTICLE_ID,
 DROP INDEX MODELEPC_ID,
 DROP INDEX SOFTWARE_ID,
 CHANGE CURRENTACTION_ID ACTIONOBSO_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE APN_ID AIRBUSPN_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE STRATEGYKEPT_ID STRATEGY_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE MPN_ID MANUFACTURERPN_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_OBSOLESCENCEDATA_AIRBUSSTATUS_ID (AIRBUSSTATUS_ID),
 ADD INDEX K_OBSOLESCENCEDATA_ACTIONOBSO_ID (ACTIONOBSO_ID),
 ADD INDEX K_OBSOLESCENCEDATA_STRATEGY_ID (STRATEGY_ID),
 ADD INDEX K_OBSOLESCENCEDATA_MANUFACTURERSTATUS_ID (MANUFACTURERSTATUS_ID),
 ADD INDEX K_OBSOLESCENCEDATA_CONSULTPERIOD_ID (CONSULTPERIOD_ID),
 ADD INDEX K_OBSOLESCENCEDATA_TYPEARTICLE_ID (TYPEARTICLE_ID),
 ADD UNIQUE UK_OBSOLESCENCEDATA_TYPEPC_TYPEARTICLE_ID (TYPEPC_TYPEARTICLE_ID),
 ADD UNIQUE UK_OBSOLESCENCEDATA_AIRBUSPN_ID_TYPEARTICLE_ID (AIRBUSPN_ID, TYPEARTICLE_ID),
 ADD UNIQUE UK_OBSOLESCENCEDATA_SOFTWARE_ID (SOFTWARE_ID),
 ADD UNIQUE UK_OBSOLESCENCEDATA_MANUFACTURERPN_ID_TYPEARTICLE_ID (MANUFACTURERPN_ID, TYPEARTICLE_ID),
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_AIRBUSSTATUS_ID FOREIGN KEY (AIRBUSSTATUS_ID) REFERENCES AIRBUSSTATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_ACTIONOBSO_ID FOREIGN KEY (ACTIONOBSO_ID) REFERENCES ACTIONOBSO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_STRATEGY_ID FOREIGN KEY (STRATEGY_ID) REFERENCES STRATEGY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_TYPEPC_TYPEARTICLE_ID FOREIGN KEY (TYPEPC_TYPEARTICLE_ID) REFERENCES TYPEARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_MANUFACTURERSTATUS_ID FOREIGN KEY (MANUFACTURERSTATUS_ID) REFERENCES MANUFACTURERSTATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_AIRBUSPN_ID FOREIGN KEY (AIRBUSPN_ID) REFERENCES AIRBUSPN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_SOFTWARE_ID FOREIGN KEY (SOFTWARE_ID) REFERENCES SOFTWARE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_CONSULTPERIOD_ID FOREIGN KEY (CONSULTPERIOD_ID) REFERENCES CONSULTPERIOD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_MANUFACTURERPN_ID FOREIGN KEY (MANUFACTURERPN_ID) REFERENCES MANUFACTURERPN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_OBSOLESCENCEDATA_TYPEARTICLE_ID FOREIGN KEY (TYPEARTICLE_ID) REFERENCES TYPEARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PC
 DROP INDEX FK_PC_ALLOCATION_ID,
 DROP INDEX FK_PC_USAGE_ID,
 DROP INDEX FK_PC_TYPE_ID,
 CHANGE USAGE_ID BUSINESSUSAGEPC_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE ALLOCATION_ID BUSINESSALLOCATIONPC_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_PC_BUSINESSALLOCATIONPC_ID (BUSINESSALLOCATIONPC_ID),
 ADD INDEX K_PC_BUSINESSUSAGEPC_ID (BUSINESSUSAGEPC_ID),
 ADD INDEX K_PC_PRODUCTTYPEPC_ID (PRODUCTTYPEPC_ID),
 ADD CONSTRAINT FK_PC_PRODUCTTYPEPC_ID FOREIGN KEY (PRODUCTTYPEPC_ID) REFERENCES PRODUCTTYPEPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PC_BUSINESSUSAGEPC_ID FOREIGN KEY (BUSINESSUSAGEPC_ID) REFERENCES BUSINESSUSAGEPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PC_BUSINESSALLOCATIONPC_ID FOREIGN KEY (BUSINESSALLOCATIONPC_ID) REFERENCES BUSINESSALLOCATIONPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PC_ID FOREIGN KEY (ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PC_COMMUNICATIONPORT
 DROP INDEX FK_PC_COMMUNICATIONPORT_ports_ID,
 CHANGE ports_ID COMMUNICATIONPORT_ID BIGINT(20) NOT NULL,
 ADD INDEX K_PC_COMMUNICATIONPORT_COMMUNICATIONPORT_ID (COMMUNICATIONPORT_ID),
 ADD CONSTRAINT FK_PC_COMMUNICATIONPORT_PC_ID FOREIGN KEY (PC_ID) REFERENCES PC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PC_COMMUNICATIONPORT_COMMUNICATIONPORT_ID FOREIGN KEY (COMMUNICATIONPORT_ID) REFERENCES COMMUNICATIONPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PLACE
 DROP INDEX FK_PLACE_BUILDING_FK,
 DROP INDEX NAME,
 CHANGE BUILDING_FK BUILDING_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_PLACE_BUILDING_ID (BUILDING_ID),
 ADD UNIQUE UK_PLACE_NAME (NAME),
 ADD CONSTRAINT FK_PLACE_BUILDING_ID FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PLACE_STORERELATION
 DROP INDEX FK_PLACE_STORERELATION_STORES_ID,
 CHANGE STORES_ID STORERELATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_PLACE_STORERELATION_STORERELATION_ID (STORERELATION_ID),
 ADD CONSTRAINT FK_PLACE_STORERELATION_PLACE_ID FOREIGN KEY (PLACE_ID) REFERENCES PLACE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PLACE_STORERELATION_STORERELATION_ID FOREIGN KEY (STORERELATION_ID) REFERENCES STORERELATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PRODUCTTYPEPC_TRANSLATION
 DROP INDEX FK_PRODUCTTYPEPC_TRANSLATION_translations_ID,
 CHANGE ProductTypePC_ID PRODUCTTYPEPC_ID BIGINT(20) NOT NULL,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 ADD INDEX K_PRODUCTTYPEPC_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_PRODUCTTYPEPC_TRANSLATION_PRODUCTTYPEPC_ID FOREIGN KEY (PRODUCTTYPEPC_ID) REFERENCES PRODUCTTYPEPC (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_PRODUCTTYPEPC_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RACK
 ADD CONSTRAINT FK_RACK_ID FOREIGN KEY (ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ROLE
 DROP INDEX LABEL,
 ADD UNIQUE UK_ROLE_LABEL (LABEL);

ALTER TABLE SERVICE
 DROP INDEX NAME,
 ADD UNIQUE UK_SERVICE_NAME (NAME);

ALTER TABLE SOFTWARE
 DROP INDEX UNQ_SOFTWARE_0,
 DROP INDEX IX_SOFTWARE_UNQ_SOFTWARE_0,
 CHANGE VERSION VERSIONLABEL VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
 CHANGE _VERSION VERSION BIGINT(20) NULL DEFAULT NULL,
 ADD UNIQUE UK_SOFTWARE_NAME_VERSIONLABEL (NAME, VERSIONLABEL);

ALTER TABLE SOFTWARE_ARTICLE
 DROP INDEX FK_SOFTWARE_ARTICLE_equipments_ID,
 CHANGE softwares_ID SOFTWARE_ID BIGINT(20) NOT NULL,
 CHANGE equipments_ID ARTICLE_ID BIGINT(20) NOT NULL,
 ADD INDEX K_SOFTWARE_ARTICLE_ARTICLE_ID (ARTICLE_ID),
 ADD CONSTRAINT FK_SOFTWARE_ARTICLE_SOFTWARE_ID FOREIGN KEY (SOFTWARE_ID) REFERENCES SOFTWARE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_SOFTWARE_ARTICLE_ARTICLE_ID FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE STORERELATION
 DROP INDEX FK_STORERELATION_ARTICLE_ID,
 DROP INDEX FK_STORERELATION_PLACE_ID,
 ADD INDEX K_STORERELATION_PLACE_ID (PLACE_ID),
 ADD INDEX K_STORERELATION_ARTICLE_ID (ARTICLE_ID),
 ADD CONSTRAINT FK_STORERELATION_ARTICLE_ID FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_STORERELATION_PLACE_ID FOREIGN KEY (PLACE_ID) REFERENCES PLACE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE STRATEGY_TRANSLATION
 DROP INDEX FK_STRATEGY_TRANSLATION_translations_ID,
 CHANGE translations_ID TRANSLATION_ID BIGINT(20) NOT NULL,
 CHANGE Strategy_ID STRATEGY_ID BIGINT(20) NOT NULL,
 ADD INDEX K_STRATEGY_TRANSLATION_TRANSLATION_ID (TRANSLATION_ID),
 ADD CONSTRAINT FK_STRATEGY_TRANSLATION_STRATEGY_ID FOREIGN KEY (STRATEGY_ID) REFERENCES STRATEGY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_STRATEGY_TRANSLATION_TRANSLATION_ID FOREIGN KEY (TRANSLATION_ID) REFERENCES TRANSLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SUPPLIER
 DROP INDEX NAME,
 ADD UNIQUE UK_SUPPLIER_NAME (NAME);

ALTER TABLE SWITCH
 ADD CONSTRAINT FK_SWITCH_ID FOREIGN KEY (ID) REFERENCES RACK (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TOOL
 DROP INDEX NAME,
 CHANGE COMMENT_FK COMMENT_ID BIGINT(20) NULL DEFAULT NULL,
 CHANGE INSTALLATION_FK INSTALLATION_ID BIGINT(20) NULL DEFAULT NULL,
 ADD INDEX K_TOOL_COMMENT_ID (COMMENT_ID),
 ADD INDEX K_TOOL_INSTALLATION_ID (INSTALLATION_ID),
 ADD UNIQUE UK_TOOL_NAME (NAME),
 ADD CONSTRAINT FK_TOOL_COMMENT_ID FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_TOOL_INSTALLATION_ID FOREIGN KEY (INSTALLATION_ID) REFERENCES INSTALLATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TYPEARTICLE
 DROP INDEX LABEL,
 ADD UNIQUE UK_TYPEARTICLE_LABEL (LABEL);

-- Clean the TYPEARTICLE_AIRBUSPN table before adding constraints
DELETE FROM TYPEARTICLE_AIRBUSPN
 WHERE AIRBUSPN_ID NOT IN (SELECT ID FROM AIRBUSPN);

ALTER TABLE TYPEARTICLE_AIRBUSPN
 DROP INDEX FK_TYPEARTICLE_AIRBUSPN_AIRBUSPN_ID,
 ADD INDEX K_TYPEARTICLE_AIRBUSPN_AIRBUSPN_ID (AIRBUSPN_ID),
 ADD CONSTRAINT FK_TYPEARTICLE_AIRBUSPN_TYPEARTICLE_ID FOREIGN KEY (TYPEARTICLE_ID) REFERENCES TYPEARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_TYPEARTICLE_AIRBUSPN_AIRBUSPN_ID FOREIGN KEY (AIRBUSPN_ID) REFERENCES AIRBUSPN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USER
 DROP INDEX LOGIN,
 ADD UNIQUE UK_USER_LOGIN (LOGIN);

ALTER TABLE USER_ROLE
 DROP INDEX FK_USER_ROLES_ROLE_ID,
 ADD INDEX K_USER_ROLE_ROLE_ID (ROLE_ID),
 ADD CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
 ADD CONSTRAINT FK_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE VARIOUS
 ADD CONSTRAINT FK_VARIOUS_ID FOREIGN KEY (ID) REFERENCES ARTICLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

