--
-- UPDATE BOA DATABASE FROM VERSION 2.4 TO VERSION 2.4 PATCH
--

-- UPDATE BOA DATABASE FOR BOA-DM-108

-- ADD OPERATINGSYSTEM INTO SOFTWARE TABLE

ALTER TABLE SOFTWARE
  ADD OPERATINGSYSTEM BOOLEAN NULL DEFAULT 0;
