--
-- UPDATE BOA DATABASE FROM VERSION 2.2 TO VERSION 2.3
--

-- UPDATE BOA DATABASE FOR BOA-DM-45

-- ADD OF NBSCREENS ATTRIBUTE INTO PC
ALTER TABLE `PC`
ADD `NBSCREENS` INT NULL DEFAULT NULL AFTER `FUNCTION`;


-- UPDATE BOA DATABASE FOR BOA-DM-44

-- UPDATE LABEL IN ACTION TABLE: SET "Creation" INSTEAD OF "Acquisition"
UPDATE ACTION
SET LABEL = "Creation"
WHERE LABEL = "Acquisition";

-- UPDATE ACTION DATE TO THE ARTICLE CREATION DATE
UPDATE ACTION
JOIN HISTORY ON HISTORY.ID = ACTION.HISTORY_FK
JOIN ARTICLE ON ARTICLE.HISTORY = HISTORY.ID
SET ACTION.DATE = ARTICLE.CREATIONDATE
WHERE ACTION.LABEL = "Creation"
AND TIMEDIFF(ARTICLE.CREATIONDATE, ACTION.DATE) > MAKETIME(0,0,1);


-- UPDATE BOA DATABASE FOR BOA-DM-43

-- ADD TOOL TABLE

CREATE TABLE `TOOL` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `INSTALLATION_FK` bigint(20) DEFAULT NULL,
  `PERSONINCHARGE` varchar(40) DEFAULT NULL,
  `LOANDATE` date DEFAULT NULL,
  `LOANDUEDATE` date DEFAULT NULL,
  `COMMENT_FK` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ADD CONTAINS_TOOL_ARTICLE TABLE

CREATE TABLE `CONTAINS_TOOL_ARTICLE` (
  `ID` bigint(20) NOT NULL,
  `COMMENT` varchar(300) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `TOOL_FK` bigint(20) DEFAULT NULL,
  `ARTICLE_FK` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTAINS_TOOL_ARTICLE_TOOL_FK` (`TOOL_FK`),
  KEY `FK_CONTAINS_TOOL_ARTICLE_ARTICLE_FK`(`ARTICLE_FK`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ADD CONTAINS_PLACE_TOOL TABLE

CREATE TABLE `CONTAINS_PLACE_TOOL` (
  `ID` bigint(20) NOT NULL,
  `PRECISELOCATION` varchar(50) DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `PLACE_FK` bigint(20) DEFAULT NULL,
  `TOOL_FK` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTAINS_PLACE_TOOL_PLACE_FK` (`PLACE_FK`),
  KEY `FK_CONTAINS_PLACE_TOOL_TOOL_FK`(`TOOL_FK`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

